name: Scheduled Tasks

on:
  schedule:
    # Run every 30 minutes
    - cron: "*/30 * * * *"
    # Run daily
    - cron: "0 1 * * *"

jobs:
  scheduler-notification-task:
    runs-on: ubuntu-latest
    # Run every 30 minutes (minimum interval for GitHub Actions)
    if: github.event.schedule == '*/30 * * * *'

    steps:
      - name: Scheduler Notification Task
        run: |
          curl -X POST https://lpxyvefkjs3mcjtcn4sngbmfye0uojem.lambda-url.ap-east-1.on.aws/api/scheduler/execute_tasks/ \
          -H "Content-Type: application/json" \
          -H "X-Custom-Token: lzLc2cLXu2rRQgp4s2mh1IACELGIYe3vXuCz3W52rVKMlt26a660UBGHlctdfF6D"

  scheduler-monthly-registration-sms:
    runs-on: ubuntu-latest
    # Run daily to check users registered one month ago
    if: github.event.schedule == '0 1 * * *'

    steps:
      - name: Monthly Registration SMS
        run: |
          curl -X POST https://lpxyvefkjs3mcjtcn4sngbmfye0uojem.lambda-url.ap-east-1.on.aws/api/scheduler/send-registration-monthly-sms/ \
          -H "Content-Type: application/json" \
          -H "X-Custom-Token: lzLc2cLXu2rRQgp4s2mh1IACELGIYe3vXuCz3W52rVKMlt26a660UBGHlctdfF6D"
